/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ankit_example_NDK */

#ifndef _Included_com_ankit_example_NDK
#define _Included_com_ankit_example_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ankit_example_NDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ankit_example_NDK_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ankit_example_NDK
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ankit_example_NDK_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
